### ISSUE TITLE
pyvo-data is not cloned

### ISSUE THREAD

**Issue by hroncok** [Sanqui/pyvo-twitter#2]
```
$ python pyvo-twitter.py tweet-next  --dry
Traceback (most recent call last):
  File "pyvo-twitter.py", line 150, in <module>
    main()
  File "/home/churchyard/Dokumenty/pyvo-twitter/__env__/lib64/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/churchyard/Dokumenty/pyvo-twitter/__env__/lib64/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/churchyard/Dokumenty/pyvo-twitter/__env__/lib64/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/churchyard/Dokumenty/pyvo-twitter/__env__/lib64/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/churchyard/Dokumenty/pyvo-twitter/__env__/lib64/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "pyvo-twitter.py", line 97, in announce_next
    db = get_db(config.data_dir)
  File "/home/churchyard/Dokumenty/pyvo-twitter/__env__/lib64/python3.5/site-packages/pyvodb/load.py", line 33, in get_db
    load_from_directory(db, directory)
  File "/home/churchyard/Dokumenty/pyvo-twitter/__env__/lib64/python3.5/site-packages/pyvodb/load.py", line 57, in load_from_directory
    data = dict_from_directory('.', directory)
  File "/home/churchyard/Dokumenty/pyvo-twitter/__env__/lib64/python3.5/site-packages/pyvodb/load.py", line 39, in dict_from_directory
    for filename in os.listdir(os.path.join(root, directory)):
FileNotFoundError: [Errno 2] No such file or directory: 'pyvo-data/.'
```

I think this should clone the repo if not there and pull if it is there.

**Comment by Sanqui** [comment]
>I think this should clone the repo if not there and pull if it is there.
It was written to do this, of course, but by accident only `tweet-today` did.
